server:
  port: 84
  
spring:
  application:
    name: cryptography
  webflux:
    base-path: /cryptography
    
eureka:
  client:
    region: default
    service-url:
      defaultZone: http://127.0.0.1:83/eureka
